"""add_depth_column

Revision ID: 4a3c2e96f04a
Revises: a081cd89290b
Create Date: 2026-06-13 07:50:36.009532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3c2e96f04a'
down_revision: Union[str, None] = 'a081cd89290b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_progress', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('audit_sessions', sa.Column('depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_sessions', 'depth')
    op.drop_column('audit_progress', 'depth')
    # ### end Alembic commands ###
