"""add pages_depth_map column

Revision ID: 74cff54d8f61
Revises: 4a3c2e96f04a
Create Date: 2026-06-13 09:21:55.189785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cff54d8f61'
down_revision: Union[str, None] = '4a3c2e96f04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_progress', sa.Column('pages_depth_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_progress', 'pages_depth_map')
    # ### end Alembic commands ###
