"""Add pricing tiers and credit billing models

Revision ID: a081cd89290b
Revises: 53891c5434a6
Create Date: 2026-06-01 20:16:33.040600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a081cd89290b'
down_revision: Union[str, None] = '53891c5434a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('plan_tier', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('credit_balance', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('billing_status', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('pay_as_you_go_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'pay_as_you_go_enabled')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_column('organizations', 'billing_status')
    op.drop_column('organizations', 'credit_balance')
    op.drop_column('organizations', 'plan_tier')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
